language: node_js
node_js:
  - "8.*"
  - "10"

# https://github.com/andywer/leakage#travis-ci
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi

branches:
  only:
    - master
    - /^greenkeeper-.*$/

before_script:
    - "npm run dist"

script:
    - "npm run test:ci"

after_success:
    - SAUCELABS=true npm run test:browser

cache:
  directories:
    - node_modules

notifications:
    email: false

sudo: false
